In [1]:
import pandas as pd
import random
import numpy as np
from tqdm import tqdm_notebook, tqdm
tqdm.pandas()
import pickle
# from pandarallel import pandarallel # for linux and mac
# pandarallel.initialize()

In [2]:
results = pd.read_csv('results.csv')
results.loc[:, 'mask'] = results.loc[:, 'mask'].str.replace('X', '')
roster = pd.read_csv('roster.csv')#.set_index('idplayer')
tournaments = pd.read_csv('tournaments.csv').set_index('idtournament')
tournaments = tournaments.loc[~tournaments.questions_total.isnull(), :]
common_tours = list(set(tournaments.index).intersection(set(results.idtournament)))
results = results.loc[results.idtournament.isin(common_tours), :]
tournaments = tournaments.loc[common_tours, :]

q_total = pd.DataFrame(results.groupby('idtournament').first()\
                       .loc[:, 'mask'].str.len()).dropna().rename(columns={'mask': 'questions_total'})
tournaments = pd.merge(tournaments.drop(columns=['questions_total']), q_total, left_index=True, right_index=True)

In [3]:
ineligible_tournaments = [1521, 1526, 1531, 1534, 1780, 1817, 1849, 1854, 1858, 1885, 1893, 1902, 1925, 1926, 1928,
                          1931, 1960, 2025, 2040, 2077, 2087, 2128, 2147, 2151, 2166, 2183, 2291, 2345, 2346, 2472,
                          2479, 2512, 2521, 2578, 2611, 2707, 2732, 2763, 2783, 2833, 3130, 3162, 3231, 3510, 3589,
                          3590, 3617, 4011, 4169, 4375, 4469, 4481, 4497, 4713, 4714, 4816, 4860, 4881, 4913, 4946,
                          4969, 4983, 4984, 4989, 4990, 4992, 5032, 5054, 5097, 5102, 5106, 5121, 5126, 5160, 5178,
                          5210, 5215, 5221, 5239, 5241, 5247, 5299, 5310,
                          # nan tours
                          1954, 1989, 1970, 1810, 1917, 2373, 2219, 1969,  314, 1824, 2102, 2241, 2249, 2014, 2220,
                          2363, 2703, 2234, 2417, 2171, 2126, 1900, 2013, 2394, 1792, 1689, 1590, 1987, 1895, 1991,
                          2119, 1951, 1899,1898, 2224, 1976, 2100
                         ]
results = results.loc[~results.idtournament.isin(ineligible_tournaments), :]
results.loc[:, 'mask'] = results.loc[:, 'mask'].apply(lambda x: list(str(x)))
roster = roster.loc[~roster.idtournament.isin(ineligible_tournaments), :]

In [4]:
results.loc[:, 'players'] = results.progress_apply(lambda row: np.sort(np.array(roster.loc[(roster.idteam == row['idteam']) & 
                                           (roster.idtournament == row['idtournament']), 'idplayer'].tolist())), axis=1)
results = results.loc[results.players.str.len() != 0, :]

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 303277/303277 [47:10<00:00, 107.14it/s]


In [5]:
READ=True
if READ:
    with open('results.pickle', 'rb') as f:
        results = pickle.load(f)
else:
    with open('results.pickle', 'wb') as f:
        pickle.dump(results, f)

In [6]:
def explode(df, lst_cols, fill_value='', preserve_index=False):
    # make sure `lst_cols` is list-alike
    if (lst_cols is not None
        and len(lst_cols) > 0
        and not isinstance(lst_cols, (list, tuple, np.ndarray, pd.Series))):
        lst_cols = [lst_cols]
    # all columns except `lst_cols`
    idx_cols = df.columns.difference(lst_cols)
    # calculate lengths of lists
    lens = df[lst_cols[0]].str.len()
    # preserve original index values    
    idx = np.repeat(df.index.values, lens)
    orders = [num for range_len in lens for num in range(range_len)]
    # create "exploded" DF
    res = (pd.DataFrame({
                col:np.repeat(df[col].values, lens)
                for col in idx_cols},
                index=idx)
             .assign(**{col:np.concatenate(df.loc[lens>0, col].values)
                            for col in lst_cols}))
    # append those rows that have empty lists
    if (lens == 0).any():
        # at least one list in cells is empty
        res = (res.append(df.loc[lens==0, idx_cols], sort=False)
                  .fillna(fill_value))
    # revert the original index order
    res = res.sort_index()
    # reset index if requested
    if not preserve_index:        
        res = res.reset_index(drop=True)
    
    res.loc[:, 'q_numb'] = orders
    return res

In [7]:
exp = explode(results.loc[:, ['idteam', 'idtournament', 'mask', 'players']], ['mask'], fill_value='', preserve_index=False)\
            .rename(columns={'mask': 'q_taken'})
exp.head(1)

idteam  idtournament                                   players q_taken  \
0     209          3236  [5974, 7474, 13601, 15624, 19298, 32017]       1   

   q_numb  
0       0

In [8]:
%%timeit -n1 -r1
# exp.loc[:, 'q_id_old'] = exp.idtournament.map(str) + "_" + exp.idteam.map(str) + "_" + exp.q_numb.map(str)
# exp.loc[:, 'q_id'] = (exp.idtournament.map(str) + "0000" + exp.idteam.map(str) + "0000" + exp.q_numb.map(str)).map(int)
exp.loc[:, 'q_id'] = exp.idtournament * 1000000000 + exp.idteam * 1000 + exp.q_numb
exp['q_taken'] = exp.q_taken.astype(int)
# len(exp.q_id.unique()) == len(exp.q_id_old.unique()) check for losses

1.22 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [9]:
exp.head(1)

idteam  idtournament                                   players  q_taken  \
0     209          3236  [5974, 7474, 13601, 15624, 19298, 32017]        1   

   q_numb           q_id  
0       0  3236000209000

## Players skills and question difficulties as numpy arrays
https://stackoverflow.com/questions/36652533/looking-up-large-sets-of-keys-dictionary-vs-numpy-array

In [10]:
skill_ids = roster.sort_values('idplayer').idplayer.unique()
skills = np.array(list(zip(skill_ids, np.random.uniform(0,1, len(skill_ids))))   )

# key_set = np.array([15,17,19])
# row_idx = np.searchsorted(skills[:,0],key_set)[key_set.argsort()]
# values = skills[row_idx, :]

In [ ]:
dif_ids = np.sort(exp.q_id.unique())
difficulties = np.array(list(zip(dif_ids, np.random.uniform(0,1, len(dif_ids))))   )

In [11]:
# row_idx = np.searchsorted(skills[:,0], key_set)[key_set.argsort()]
# values = skills[row_idx, :]
def team_performance(players):
#     row_idx = np.searchsorted(skills[:,0], key_set)[key_set.argsort()]
#     row_idx = np.searchsorted(skills[:,0], players)
#     values = skills[row_idx, 1]
    return np.mean(
        skills[np.searchsorted(skills[:,0], players), 1] 
    )
def get_difficulties_by_q_id(q_ids):
    return difficulties[np.searchsorted(difficulties[:,0], q_ids), 1]#[q_ids.argsort()]
def sigmoid(x):
    return 1 / (1 + pd.np.exp(-x))

## Learning

**Model**<br>
$p(y=1| S_{team}, \theta) = \sigma(S_{team} - \theta)$ <br>
$S_{team}$ - team skill<br>
$S_{team} = S_{player\_1} + S_{player\_2} + ... + S_{player\_N}$<br>
$\theta_j$ - difficulty of question j<br>
y - team answer, 1 for correct, 2 for incorrect<br>
$p(y_{hat}=y_{real}| S_{team}, \theta) = \sigma(S_{team} - \theta)^{y_{real}} * (1-\sigma(S_{team} - \theta))^{(1-y_{real})}$<br>
<br>
$LikelyHood = \frac{1}{N}\prod_{i=1}^{N} p(y_{hat\_i}=y_{real\_i}| S_{team}, \theta)$<br>
$log(LikelyHood) = LL = \frac{1}{N}\sum_{i=1}^{N} log(p(y_{hat\_i}=y_{real\_i}| S_{team}, \theta))=
y_{real}*log(\sigma(S_{team} - \theta)) + (1-y_{real})* log(1-\sigma(S_{team} - \theta))$<br>
<br>
$-log(LikelyHood) \rightarrow min$ w.r.t. $S_{player\_i}$ and $\theta_j$

**Derivatives:**

$\sigma'(x) = \sigma(x)*(1-\sigma(x))$

$\frac{\partial LL}{\partial \theta} = \frac{y_{real}}{\sigma(S_{team} - \theta)} * \sigma'(S_{team} - \theta) * (-1) +
\frac{1-y_{real}}{1-\sigma(S_{team} - \theta)} * (-\sigma'(S_{team} - \theta)) * (-1) = 
-y_{real}*(1-\sigma(S_{team} - \theta)) + (1-y_{real})*\sigma(S_{team} - \theta)
$<br>

$\frac{\partial LL}{\partial S_i} = \frac{y_{real}}{\sigma(S_{team} - \theta)} * \sigma'(S_{team} - \theta) +
\frac{1-y_{real}}{1-\sigma(S_{team} - \theta)} * (-\sigma'(S_{team} - \theta)) = 
y_{real}*(1-\sigma(S_{team} - \theta)) - (1-y_{real})*\sigma(S_{team} - \theta)$<br>


**Short derivatives:**

$\frac{\partial -LL}{\partial \theta} = +y_{real}*(1-\sigma(S_{team} - \theta)) - (1-y_{real})*\sigma(S_{team} - \theta)
$<br>

$\frac{\partial -LL}{\partial S_i} = -y_{real}*(1-\sigma(S_{team} - \theta)) + (1-y_{real})*\sigma(S_{team} - \theta)$<br>


**Gradient update**<br>
$S_{i\_new} = S_{i\_old} - learning\_rate * \frac{\partial LL}{\partial S_i}$<br>
$\theta_{new} = \theta_{old} - learning\_rate * \frac{\partial LL}{\partial \theta}$<br>

In [ ]:
def sgd(lr=0.01, epochs=10, batch_size=16):
    batch = exp.sample(n=batch_size)
    

In [17]:
t_perf = batch['players'].apply(lambda members: team_performance(members))

In [18]:
q_dif = batch['q_id'].apply(lambda question: get_difficulties_by_q_id(question))

In [20]:
team_sigmoid = sigmoid(t_perf - q_dif)

In [22]:
lr = 0.1
q_dif_update = lr * (batch['q_taken'] * (1-team_sigmoid) - (1-batch['q_taken'])*team_sigmoid)
difficulties[np.searchsorted(difficulties[:,0], batch['q_id']), 1] -= q_dif_update

In [23]:
skill_update = -(lr * (batch['q_taken'] * (1-team_sigmoid) - (1-batch['q_taken'])*team_sigmoid) /
                 batch['players'].str.len())

In [29]:
zeroes = np.zeros((batch_size,batch['players'].str.len().max()))

In [ ]:
for idx in range(batch_size):
    print(skills[np.searchsorted(skills[:,0], batch['players'].iloc[idx]), 1])

In [41]:
for idx in range(batch_size):
    skills[np.searchsorted(skills[:,0], batch['players'].iloc[idx]), 1] -= skill_update.iloc[idx]

[0.55964895 0.6910353  0.15193916 0.64960539 0.04649038]
[0.54773597 0.67912232 0.14002618 0.63769241 0.0345774 ]
[0.79463551 0.47940093 0.16241016 0.4066088  0.5953737  0.80056105]
[0.80125594 0.48602136 0.16903059 0.41322923 0.60199413 0.80718148]
[0.76841001 0.62753037 0.23634695 0.28896515 0.16351539]
[0.75725232 0.61637269 0.22518927 0.27780746 0.15235771]
[0.25935486 0.95127482 0.79299102 0.95562479]
[0.24439126 0.93631122 0.77802742 0.94066119]
[0.08876256 0.90818403 0.01307916 0.59447537 0.8869077  0.27444528]
[0.07892583 0.8983473  0.00324243 0.58463864 0.87707097 0.26460855]
[0.13741839 0.86195292 0.31794043 0.31840741 0.84746763 0.23598064]
[0.1451696  0.86970413 0.32569164 0.32615862 0.85521884 0.24373185]
[0.04594022 0.75717589 0.37879565 0.68536547 0.71140926 0.17251788
 0.95235363 0.00291672]
[ 0.03873937  0.74997505  0.37159481  0.67816463  0.70420841  0.16531703
  0.94515278 -0.00428413]
[0.08724148 0.1451696  0.52572232 0.60972037 0.36352078 0.86857864
 0.47049376 0.9

In [35]:
batch['players'].iloc[0]

array([ 79580,  84041, 108140, 108781, 108782])

In [26]:
np.array(batch['players'].tolist()).shape


(16,)

In [ ]:
batch['players'].str.len().max()

In [ ]:
batch['players'].apply(lambda x: x)

In [ ]:
sum(exp.players.str.len() == 0)

In [ ]:
batch['players'].str.len()

In [ ]:
batch['players']